package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"sync"

	"github.com/bwmarrin/discordgo"
)

var sites sync.Map

// ================= ID =================

func randomID() string {
	b := make([]byte, 6)
	rand.Read(b)
	return hex.EncodeToString(b)
}

// ================= BEAUTIFUL SITE GENERATOR =================

func generateSite(prompt string) string {

	title := strings.Title(prompt)

	return fmt.Sprintf(`
<!DOCTYPE html>
<html>
<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>%s</title>

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">

<style>

*{
margin:0;
padding:0;
box-sizing:border-box;
}

body{
font-family:'Inter',sans-serif;
background:#0f0f0f;
color:white;
overflow-x:hidden;
}

.hero{
height:100vh;
display:flex;
flex-direction:column;
justify-content:center;
align-items:center;
text-align:center;
padding:20px;
background:
radial-gradient(circle at top,#7c3aed 0%%,#0f0f0f 60%%);
}

.hero h1{
font-size:72px;
font-weight:800;
margin-bottom:20px;
animation:fadeUp 1s ease;
}

.hero p{
font-size:22px;
opacity:.8;
max-width:700px;
animation:fadeUp 1.3s ease;
}

.btn{
margin-top:40px;
padding:18px 40px;
border:none;
border-radius:14px;
background:#7c3aed;
color:white;
font-size:18px;
cursor:pointer;
transition:.3s;
animation:fadeUp 1.6s ease;
}

.btn:hover{
transform:translateY(-3px);
background:#8b5cf6;
}

.section{
padding:120px 10%%;
}

.cards{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(260px,1fr));
gap:25px;
margin-top:50px;
}

.card{
background:#18181b;
padding:40px;
border-radius:24px;
transition:.3s;
border:1px solid #27272a;
}

.card:hover{
transform:translateY(-8px);
border-color:#7c3aed;
}

.card h3{
font-size:24px;
margin-bottom:15px;
}

.footer{
padding:50px;
text-align:center;
opacity:.5;
}

@keyframes fadeUp{
from{
opacity:0;
transform:translateY(30px);
}
to{
opacity:1;
transform:translateY(0);
}
}

</style>

</head>

<body>

<section class="hero">

<h1>%s</h1>

<p>
Современный AI-powered сервис нового поколения.
Быстро. Красиво. Эффективно.
</p>

<button class="btn">
Начать сейчас
</button>

</section>

<section class="section">

<h2 style="font-size:48px">
Почему выбирают нас
</h2>

<div class="cards">

<div class="card">
<h3>⚡ Быстро</h3>
<p>Мгновенная работа и высокая производительность.</p>
</div>

<div class="card">
<h3>🎨 Красиво</h3>
<p>Премиальный дизайн уровня SaaS.</p>
</div>

<div class="card">
<h3>🚀 Масштабируемо</h3>
<p>Подходит для роста бизнеса.</p>
</div>

</div>

</section>

<section class="section">

<h2 style="font-size:48px">
Готов к запуску
</h2>

<p style="margin-top:20px;font-size:20px;opacity:.8">
Полностью адаптивный современный сайт.
</p>

</section>

<div class="footer">
Generated by AI Builder
</div>

</body>
</html>
`, title, title)
}

// ================= CREATE SITE =================

func createSite(prompt string) string {

	id := randomID()

	html := generateSite(prompt)

	sites.Store(id, html)

	return id
}

// ================= SITE PAGE =================

func siteHandler(w http.ResponseWriter, r *http.Request) {

	id := strings.TrimPrefix(r.URL.Path, "/site/")

	v, ok := sites.Load(id)

	if !ok {
		http.NotFound(w, r)
		return
	}

	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(v.(string)))
}

// ================= AI =================

func smartReply(prompt string) string {

	p := strings.ToLower(prompt)

	if strings.Contains(p, "сайт") {

		id := createSite(prompt)

		return "✅ Сайт создан:\nhttp://localhost:8080/site/" + id
	}

	return "🤖 Напиши:\nсделай сайт для кофейни"
}

// ================= DISCORD =================

func runBot() {

	token := os.Getenv("DISCORD_TOKEN")

	if token == "" {
		log.Fatal("нет DISCORD_TOKEN")
	}

	dg, err := discordgo.New("Bot " + token)
	if err != nil {
		log.Fatal(err)
	}

	dg.AddHandler(func(s *discordgo.Session, m *discordgo.MessageCreate) {

		if m.Author.Bot {
			return
		}

		res := smartReply(m.Content)

		s.ChannelMessageSend(m.ChannelID, res)
	})

	err = dg.Open()
	if err != nil {
		log.Fatal(err)
	}

	log.Println("✅ BOT ONLINE")
}

// ================= UI =================

func ui(w http.ResponseWriter, r *http.Request) {

	w.Write([]byte(`
<html>
<body style="background:#111;color:white;font-family:sans-serif;padding:40px">

<h1>🚀 AI Site Builder</h1>

<form action="/generate">
<input name="prompt" style="width:400px;padding:12px">
<button>Generate</button>
</form>

</body>
</html>
`))
}

// ================= GENERATE =================

func generateHandler(w http.ResponseWriter, r *http.Request) {

	prompt := r.URL.Query().Get("prompt")

	id := createSite(prompt)

	http.Redirect(w, r, "/site/"+id, 302)
}

// ================= MAIN =================

func main() {

	go runBot()

	http.HandleFunc("/", ui)
	http.HandleFunc("/generate", generateHandler)
	http.HandleFunc("/site/", siteHandler)

	log.Println("🚀 SERVER :8080")

	http.ListenAndServe(":8080", nil)
}
